"""Turn a UI-less script into an interactive one.

Hard rule: the original file is NEVER modified. Everything lands in
`~/.scriptforge/built/<name>` and the original keeps working untouched.
"""

from __future__ import annotations

import os
import re
import shlex
from dataclasses import dataclass
from pathlib import Path

from .parser.ir import Kind, Lang, ScriptIR

IS_WINDOWS = os.name == "nt"

BUILT_DIR = Path.home() / ".scriptforge" / "built"

BANNER = "# generated by scriptforge (AIHAM AM) - do not edit; regenerate instead"


def _out_suffix(ir: ScriptIR) -> str:
    """PowerShell wrappers must keep .ps1 to stay double-clickable."""
    if ir.lang is Lang.POWERSHELL:
        return ".ps1"
    if ir.lang is Lang.BATCH:
        return ".cmd"
    if ir.lang is Lang.PYTHON:
        return ".py"
    return ".sh"


@dataclass
class RewriteResult:
    source: Path
    generated: Path
    ok: bool
    kind: str
    message: str
    fields: list[str]


def rewrite(ir: ScriptIR, out_dir: Path | None = None, force: bool = False) -> RewriteResult:
    """Generate an interactive wrapper for a SKELETAL/OPAQUE script."""
    target_dir = Path(out_dir) if out_dir else BUILT_DIR
    if not ir.buildable:
        return RewriteResult(
            ir.path, ir.path, False, ir.kind.value,
            "opaque entry point - nothing to rewrite, launch with freeform args",
            [],
        )

    target_dir.mkdir(parents=True, exist_ok=True)
    stem = ir.path.stem
    suffix = _out_suffix(ir)
    out = target_dir / f"{stem}{suffix}"

    if out.exists() and not force:
        return RewriteResult(ir.path, out, True, ir.kind.value, "already generated (use force)", [])

    try:
        if ir.lang is Lang.POWERSHELL:
            body = _build_powershell_wrapper(ir)
        elif ir.lang is Lang.BASH:
            body = _build_bash_wrapper(ir)
        else:
            body = _build_python_wrapper(ir)
        out.write_text(body, encoding="utf-8")
        if not IS_WINDOWS:
            out.chmod(0o755)
    except Exception as exc:  # noqa: BLE001
        return RewriteResult(ir.path, out, False, ir.kind.value, f"failed: {exc}", [])

    fields = re.findall(r"ask_field (\w+)", body)
    return RewriteResult(
        ir.path, out, True, ir.kind.value,
        f"wrote {out}", fields,
    )


def _argv_template(ir: ScriptIR) -> tuple[str, list[str]]:
    """Return (a bash array literal of the fixed argv, the fields to ask for).

    For `cline-acct1`:
        line = `cline --config /path/settings "$@"`
    we hard-code the constant part and turn `"$@"` into prompted fields.
    """
    source = ir.path.read_text(errors="replace")
    for line in source.splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        # Skip shebang/usage/set lines; want the payload command.
        if s.startswith(("usage", "case", "if", "esac", "fi", "done")):
            continue
        if "$@" in s or "${@}" in s or "$*" in s:
            parts = shlex.split(s.replace('"$@"', " ").replace("'$@'", " ").replace('"${@}"', " "))
            return " ".join(shlex.quote(p) for p in parts), []
    # Nothing with "$@" -> treat the whole script as an opaque command.
    return f"bash {shlex.quote(str(ir.path))}", []


def _build_bash_wrapper(ir: ScriptIR) -> str:
    cmd, _ = _argv_template(ir)
    name = ir.name
    desc = ir.description or f"interactive wrapper for {name}"
    detected = " ".join(ir.detected_tools)
    warn = ""
    if detected:
        warn = f'echo "[!] runs: {detected}" >&2\n'

    return f"""#!/usr/bin/env bash
{BANNER}
# source : {ir.path}
# purpose: {desc}
set -euo pipefail

NAME="{name}"
CMD=({cmd})

ask_field() {{
  local name="$1" prompt="$2" default="$3" reply
  if ! read -rp "$prompt{{:+$prompt}}: " reply; then
    echo   # EOF: stdin closed, nothing left to ask
    exit 0
  fi
  if [ -n "$default" ] && [ -z "$reply" ]; then
    reply="$default"
  fi
  CMD+=("$reply")
}}

{warn}
echo "=== $NAME ==="

# Guard against a non-interactive caller that would otherwise spin here.
rounds=0
while true; do
  cat <<'MENU'
  1) run as-is      2) add a value     0) quit
MENU
  if ! read -r -p "choice: " c; then
    echo
    exit 0
  fi
  case "$c" in
    1) exec "${{CMD[@]}}" ;;
    2) ask_field arg "value" "" ;;
    0|q|Q) exit 0 ;;
    "") ;;
    *) echo "invalid: $c" ;;
  esac
  rounds=$((rounds + 1))
  if [ "$rounds" -ge 500 ]; then
    echo "too many menu rounds - aborting" >&2
    exit 0
  fi
done
"""


def _build_python_wrapper(ir: ScriptIR) -> str:
    target = ir.path
    name = ir.name
    desc = ir.description or f"interactive wrapper for {name}"
    return f'''#!/usr/bin/env python3
"""{BANNER}
source : {target}
purpose: {desc}
"""
import subprocess
import sys

TARGET = {str(target)!r}


def ask(prompt: str, default: str = "") -> str:
    suffix = f" [{{default}}]" if default else ""
    try:
        reply = input(f"{{prompt}}{{suffix}}: ").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(130)
    return reply or default


def main() -> int:
    args = list(sys.argv[1:])
    print(f"=== {name} ===")
    while True:
        print("\\n  1) run as-is   2) add value   0) quit")
        try:
            choice = ask("choice", "1")
        except (EOFError, KeyboardInterrupt):
            print()
            return 0
        if choice == "0":
            return 0
        if choice == "2":
            args.append(ask("value"))
            continue
        try:
            return subprocess.call([sys.executable, TARGET, *args])
        except FileNotFoundError:
            print(f"target vanished: {{TARGET}}")
            return 127
        except KeyboardInterrupt:
            return 130


if __name__ == "__main__":
    sys.exit(main())
'''


def _build_powershell_wrapper(ir: ScriptIR) -> str:
    """Windows counterpart of the bash wrapper."""
    target = str(ir.path)
    name = ir.name
    desc = ir.description or f"interactive wrapper for {name}"
    return f'''# {BANNER}
# source: {target}
# purpose: {desc}
$ErrorActionPreference = "Stop"
$Target = "{target}"
$Extra = New-Object System.Collections.ArrayList

function Ask-Value {{
    param([string]$Prompt, [string]$Default = "")
    if ($Default) {{
        $reply = Read-Host "$Prompt [$Default]"
    }} else {{
        $reply = Read-Host $Prompt
    }}
    if ([string]::IsNullOrWhiteSpace($reply)) {{ $reply = $Default }}
    return $reply
}}

Write-Host "=== {name} ==="
while ($true) {{
    Write-Host "  1) run as-is   2) add value   0) quit"
    $choice = Read-Host "choice"
    switch ($choice) {{
        "1" {{ & $Target @Extra; exit $LASTEXITCODE }}
        "2" {{ [void]$Extra.Add((Ask-Value "value")); continue }}
        "0" {{ exit 0 }}
        default {{ Write-Host "invalid: $choice" }}
    }}
}}
'''